### ISSUE TITLE
Do not load local profile if wd is different in the child process

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/callr#139]
Because then it is not there. Cf: https://github.com/rstudio/renv/issues/297

**Comment by lnyman1** [comment]
+1. I have tracked down the same issue I was seeing to the latest release in callr. The same issue happens when calling devtools::check() with packrat.

**Comment by nteetor** [comment]
I haven't submitted a PR to callr before, but I can take a stab at one, especially if this could help resolve r-lib/rcmdcheck#116.

**Comment by gaborcsardi** [comment]
@nteetor Sounds good. We need to decide how exactly we want to do this, perhaps the `wd` argument needs to be involved as well.

**Comment by mlell** [comment]
This bug also makes it impossible to build or install local packages inside an renv-controlled environment.

renv::init()
install.packages("devtools")
dir.create("utils")
devtools::create("utils/test", rstudio = FALSE, open = FALSE)

remotes::install_local("utils/test") # fails
devtools::build("utils/test")        # fails
##   Error in file(filename, "r", encoding = encoding) : 
##     cannot open the connection
##   Calls: source -> file
##   In addition: Warning message:
##     In file(filename, "r", encoding = encoding) :
##     cannot open file 'renv/activate.R': No such file or directory
##   Execution halted
## Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
##                       System command error

**Comment by gaborcsardi** [comment]
Fixed in d7adfaf4de9741f026da9a7e862058e4d5c926c0

**Comment by lofung** [comment]
is not fixed.

i tried to run ````devtools::install_version('callr', version = '3.3.0')````

it comes back to 

````  cannot open file 'renv/activate.R': No such file or directory````
again

in a full circle.

**Comment by gaborcsardi** [comment]
@lofung I cannot reproduce this. If it is a problem for you, then please open a new issue with some code that reproduces this for you.
